# 应用服务 WEB 访问端口
server:
  port: 8080

spring:
  elasticsearch:
    uris: 10.83.40.232:9200
    # 用户名
    username:
    # 密码
    password:
    # 连接超时时间
    connection-timeout: 1000

  logging:
    level:
      root: info

file:
  tempFilePath: /temp
